name: Style

# Controls when the workflow will run
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: StyLua
        uses: JohnnyMorganz/stylua-action@1.0.0
        with:
            token: ${{ secrets.GITHUB_TOKEN }}
            # CLI arguments
            args: --check .
